### ISSUE TITLE
Not working with current API

### ISSUE THREAD

**Issue by tobi-tobsen** [Jan200101/ShellyPy#1]
Hi, I just tried to use the your package provided via https://pypi.org/project/ShellyPy/
Unfortunatley, it doesn't work with my Shelly 1PM (20200206-083604/v1.5.10).
If I change line 
https://github.com/Jan200101/ShellyPy/blob/81c64c21579eeab5c39d2d083cb5c6a771fc8c69/ShellyPy/wrapper.py#L146
to 
`return self.post("status")`
it works like expected.

**Comment by Jan200101** [comment]
Thanks for pointing that out.
I'll push an update fixing this among other things ASAP

**Comment by Jan200101** [comment]
the issue should be fixed with 209a0b958f694bd5ad2f0f691bf52893584438bf and has already been pushed to PyPi
