### ISSUE TITLE
Shelly Plus 1 PM

### ISSUE THREAD

**Issue by emmerav** [Jan200101/ShellyPy#3]
Hi,

I've added a new Shelly device (Shelly Plus 1 PM) in my network but unfotunately it has different HTTP commands.
For example the status request has changed 
from 
http://192.168.1.102/status 
to 
http://192.168.1.102/rpc/Switch.GetStatus?id=0

Are you planning to update your project to manage these new devices ?
Thanks

**Comment by Jan200101** [comment]
Shelly Plus (and Shelly Pro) devices changed the the Gen 2 API which is RPC based.

Since ShellyPy was essentially just a thing requests wrapper that correctly delt with limitation I don't think its worth it to rework this python module for the new API, but I am working on a C library to interact with the Gen 1 and Gen 2 API as well as a python wrapper for that.

**Comment by emmerav** [comment]
Thanks Jan200101.
For different reasons my project is written in Python (I cannot change language for the moment). So it would be very helpful also an upgrade of your ShellyPy library. 
Hope to hear you soon.

**Comment by Jan200101** [comment]
when libshelly is done you don't have to change to a different language, I aim to be python compatible.

But you are right, it would be better if I update this library to support gen2 devices and am in the process of doing so.
I cannot give an estimate on how long that will take, but I would guess it will be done next week

**Comment by emmerav** [comment]
Nice news!
Thk

**Comment by Jan200101** [comment]
Should be implemented by 7994d6625fc91c85a9ee9e166263d109e53fe7d4, tested against the Shelly Plus 1 PM

I've added generation detection so you can use Gen 1 and Gen 2 devices with the standard Shelly class.

HTTP Auth is still a bit wonky with the Gen 2 devices and is currently not supported

**Comment by emmerav** [comment]
ok Jan, I'll update files and test them with both Gen in the same home
network.
Grazie mille !

Il giorno sab 12 mar 2022 alle ore 13:58 Jan ***@***.***> ha
scritto:
